# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-12-04 22:43:30
"""
import arcpy
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def Model(DEPARTEMENT_shp="H:\\Projet_perso\\ENR\\Data\\SHP\\DEPARTEMENT.shp", perimetre_habitation_WGS84_shp="H:\\Projet_perso\\ENR\\Data\\SHP\\perimetre_habitation_WGS84.shp", FR_eoliennes_shp="H:\\Projet_perso\\ENR\\Data\\SHP\\FR_eoliennes.shp", Vent_Moyen_N160_Metropole_Corse_shp="H:\\Projet_perso\\ENR\\Data\\SHP\\Vent_Moyen_N160_Metropole_Corse.shp", Expression="NOM_DEPT = 'GIRONDE'", Relation="INTERSECT", Distance_valeur_ou_champ_="2 Kilometers", Type_de_fusion="LIST", Expression_2_="FF_moyen_l >= 7", Relation_2_="INTERSECT", Type_de_sélection="SUBSET_SELECTION", Distance_valeur_ou_champ_2_="3 Kilometers", Type_de_fusion_2_="ALL", zone_très_potentielle_SF="H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb\\Gironde_ZNH_M_unipartie_SF"):  # Wind Turbine Optimal Zone Selector

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Sélection du département  d'intérêt (Sélectionner une couche par attributs) (management)
    Département_sélectionné, Total_2_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=DEPARTEMENT_shp.__str__().format(**locals(),**globals())if isinstance(DEPARTEMENT_shp, str) else DEPARTEMENT_shp, selection_type="NEW_SELECTION", where_clause=Expression.__str__().format(**locals(),**globals())if isinstance(Expression, str) else Expression)

    # Process: Copie du département d'interêt (Copier des entités) (management)
    Commune_d'interêt = "H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb\\Gironde"
    arcpy.management.CopyFeatures(in_features=Département_sélectionné, out_feature_class=Commune_d'interêt)

    # Process: Effacer (Effacer) (analysis)
    Gironde_sans_habit = "H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb\\Gironde_sans_habit"
    arcpy.analysis.Erase(in_features=Commune_d'interêt, erase_features=perimetre_habitation_WGS84_shp.__str__().format(**locals(),**globals())if isinstance(perimetre_habitation_WGS84_shp, str) else perimetre_habitation_WGS84_shp, out_feature_class=Gironde_sans_habit)

    # Process: Sélectionner une couche par localisation (Sélectionner une couche par localisation) (management)
    mat_de_vent_dans_Grironde_sans_habitation, Noms_de_couche_en_sortie, Total = arcpy.management.SelectLayerByLocation(in_layer=[FR_eoliennes_shp], overlap_type=Relation.__str__().format(**locals(),**globals())if isinstance(Relation, str) else Relation, select_features=Gironde_sans_habit)

    # Process: Sélectionner une couche par attributs (Sélectionner une couche par attributs) (management)
    Vent_Moyen_N160_Metropole_Co3, Total_4_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=Vent_Moyen_N160_Metropole_Corse_shp.__str__().format(**locals(),**globals())if isinstance(Vent_Moyen_N160_Metropole_Corse_shp, str) else Vent_Moyen_N160_Metropole_Corse_shp, where_clause=Expression_2_.__str__().format(**locals(),**globals())if isinstance(Expression_2_, str) else Expression_2_)

    # Process: Sélectionner une couche par localisation (2) (Sélectionner une couche par localisation) (management)
    Vent_Moyen_N160_Metropole_Co3_2_, Noms_de_couche_en_sortie_2_, Total_3_ = arcpy.management.SelectLayerByLocation(in_layer=[Vent_Moyen_N160_Metropole_Co3], overlap_type=Relation_2_.__str__().format(**locals(),**globals())if isinstance(Relation_2_, str) else Relation_2_, select_features=Gironde_sans_habit, selection_type=Type_de_sélection.__str__().format(**locals(),**globals())if isinstance(Type_de_sélection, str) else Type_de_sélection)

    # Process: Copier des entités (Copier des entités) (management)
    Mat_eol_160_ZNH = "H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb\\Mat_eol_160_ZNH"
    arcpy.management.CopyFeatures(in_features=mat_de_vent_dans_Grironde_sans_habitation, out_feature_class=Mat_eol_160_ZNH)

    # Process: Zone tampon (Zone tampon) (analysis)
    Vent_Moyen_N160_Metro_Buffer = "H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb\\Mat_vent_160_ZNH_Buffer"
    arcpy.analysis.Buffer(in_features=Mat_eol_160_ZNH, out_feature_class=Vent_Moyen_N160_Metro_Buffer, buffer_distance_or_field=Distance_valeur_ou_champ_.__str__().format(**locals(),**globals())if isinstance(Distance_valeur_ou_champ_, str) else Distance_valeur_ou_champ_, dissolve_option=Type_de_fusion.__str__().format(**locals(),**globals())if isinstance(Type_de_fusion, str) else Type_de_fusion)

    # Process: Effacer (2) (Effacer) (analysis)
    Gironde_ZNH_M = "H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb\\Gironde_ZNH_M"
    arcpy.analysis.Erase(in_features=Gironde_sans_habit, erase_features=Vent_Moyen_N160_Metro_Buffer, out_feature_class=Gironde_ZNH_M)

    # Process: Multi-parties vers une partie (Multi-parties vers une partie) (management)
    Zone_potentielle_pour_infrastructure_éoloienne = "H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb\\Gironde_ZNH_M_unipartie"
    arcpy.management.MultipartToSinglepart(in_features=Gironde_ZNH_M, out_feature_class=Zone_potentielle_pour_infrastructure_éoloienne)

    # Process: Copier des entités (3) (Copier des entités) (management)
    vent_NPH = "H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb\\vent_NPH"
    arcpy.management.CopyFeatures(in_features=Vent_Moyen_N160_Metropole_Co3_2_, out_feature_class=vent_NPH)

    # Process: Zone tampon (2) (Zone tampon) (analysis)
    vent_NPH_Buffer = "H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb\\vent_NPH_Buffer"
    arcpy.analysis.Buffer(in_features=vent_NPH, out_feature_class=vent_NPH_Buffer, buffer_distance_or_field=Distance_valeur_ou_champ_2_.__str__().format(**locals(),**globals())if isinstance(Distance_valeur_ou_champ_2_, str) else Distance_valeur_ou_champ_2_, dissolve_option=Type_de_fusion_2_.__str__().format(**locals(),**globals())if isinstance(Type_de_fusion_2_, str) else Type_de_fusion_2_)

    # Process: Découper (Découper) (analysis)
    arcpy.analysis.Clip(in_features=Zone_potentielle_pour_infrastructure_éoloienne, clip_features=vent_NPH_Buffer, out_feature_class=zone_très_potentielle_SF.__str__().format(**locals(),**globals())if isinstance(zone_très_potentielle_SF, str) else zone_très_potentielle_SF)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb", workspace="H:\\Projet_perso\\ENR\\Projet\\Projet_ENR\\Projet_ENR.gdb"):
        Model(*argv[1:])
